name: CI
on: [push, pull_request]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Устанавливаем pnpm (глобально для раннера)
      - uses: pnpm/action-setup@v2
        with:
          version: 9

      # Node + кеш для pnpm (работает после action-setup)
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml

      - name: Install deps
        run: pnpm install --frozen-lockfile

      - name: Typecheck
        run: pnpm run typecheck

      - name: Lint (non-blocking)
        run: pnpm run lint || true

      - name: Unit tests
        run: pnpm test -- --run

      - name: Install Playwright browsers
        run: pnpm dlx playwright install --with-deps

      - name: E2E tests
        run: pnpm run e2e
